### ISSUE TITLE
Jak dodać lomboka do swojego Eclipse :)?

### ISSUE THREAD

**Issue by srzeppa** [Strugacki/CyberCafe#1]
W tym krótkim poradniku napiszę, jak dodać lomboka do swojego eclipse :D
1. z tej strony: [**TUTAJ**](https://projectlombok.org/download.html) - należy pobrać plik o nazwie **lombok.jar**;
2. następnie należy uruchomić go (na windowsie - kliknąć prawym przyciskiem myszy, wybrać **Otwórz za pomocą -> Java**);
3. jeśli jar nie wyszukuje nam naszego IDE, należy ręcznie wybrać plik **eclipse.exe** w folderze, gdzie mamy zainstalowanego eclipse;
4. klikamy **install/update**;
5. cieszymy się zainstalowanym lombokiem :DD

Jeśli mamy w projekcie jakieś errory -> skrótem klawiszowym **alt+F5** powinniśmy móc je zlikwidować. :D W razie innych problemów, zapraszam na priv.

Pozdrawiam serdecznie :D

**Comment by goorskyy** [comment]
Dziękuję! 

Twój poradnik odmienił moje życie, wreszcie nie muszę oglądać tych wszystkich getterów i setterów, a instalacja zajęła mi tylko kilka minut! Polecam!

**Comment by Strugacki** [comment]
na linux'ie 'java -jar lombok.jar' w terminalu
